version: "3"

services:
  db:
    image: postgres:15.3-bookworm
    container_name: db
    restart: "no"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
