#cloud-config

packages:
  - docker.io

# create the docker group
groups:
  - docker

users:
  - name: ubuntu
    groups: docker
    home: /home/ubuntu
    shell: /bin/bash
    sudo: ALL=(ALL) NOPASSWD:ALL
    ssh-authorized-keys:
      - ${ssh_public_key}

# Add default auto created user to docker group
system_info:
  default_user:
    groups: [docker]

runcmd:
  - /usr/bin/sleep 10
  - /usr/bin/docker pull tutum/hello-world
  - /usr/bin/docker run -d -p ${web_port}:80 --restart=always -e SOME_VAR="SOME VALUE" tutum/hello-world